### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by elsandosgrande** [klikaba/klika-os#34]
I have noticed that there is no `LICENSE.md` file present. What is the license in use, if any?

**Comment by zpasal** [comment]
From GitHub's licensing help page:


**You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.**

**Note: If you publish your source code in a public repository on GitHub, according to the Terms of Service, other GitHub users have the right to view and fork your repository within the GitHub site. If you have already created a public repository and no longer want users to have access to it, you can make your repository private. When you convert a public repository to a private repository, existing forks or local copies created by other users will still exist.**

**Comment by elsandosgrande** [comment]
So… I take it that contributions are accepted, but derivative works are forbidden. All right. 
Given that I intended to and still intend to contribute to the project once I learn C (and apparently Objective C after taking a closer look at the language composition of the repository), I guess that I do not need a license. 

Sorry for the late response by the way 😅.
