### ISSUE TITLE
Interrupt definition for scheduling

### ISSUE THREAD

**Issue by manasvi89** [klikaba/klika-os#35]
For scheduling in process.c file, where is interrupt service routine defined for interrupt 32?

**Comment by zpasal** [comment]
It is in switch.asm

kernel/src/arch/x86_64/switch.asm

Best

**Comment by manasvi89** [comment]
I was trying to understand the scheduling of the OS and it seems that you have used a round-robin scheduling algorithm. We have confusion about where you have defined time quantum for each process and how to change it. Can you tell us?

**Comment by zpasal** [comment]
Check under kernel/src/kernel/timer.c init_kernel_timer function. It will program timer to 50Hz which triggers IRQ

**Comment by manasvi89** [comment]
We actually tried to change that value of 50Hz but it is not showing any significant impact on the time of context switch.

**Comment by zpasal** [comment]
You cannot just change constant to change frequency. Please read PIT documentation to understand how it can be configured for other frequencies https://wiki.osdev.org/Programmable_Interval_Timer

**Comment by manasvi89** [comment]
We have a problem in implementing smp in this os ,as we are not able to figure out the changes that could be done in the files . so if you could suggest us how to start.

**Comment by zpasal** [comment]
That can be quite hard topic to grasp. For sure first investigate some examples what needs to be implemented. Good starting article can be found on OsDev wiki : https://wiki.osdev.org/Symmetric_Multiprocessing
